name: PongNotPong
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - blas=1.0=mkl
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2020.1.1=0
  - cairo=1.14.12=hc4e6be7_4
  - certifi=2019.11.28=py37_1
  - cycler=0.10.0=py_2
  - ffmpeg=4.0=h01ea3c9_0
  - fontconfig=2.13.0=h5d5b041_1
  - freetype=2.9.1=hb4e5f40_0
  - gettext=0.19.8.1=h15daf44_3
  - glib=2.63.1=hd977a24_0
  - graphite2=1.3.13=h2098e52_0
  - harfbuzz=1.8.8=hb8d4a28_0
  - hdf5=1.10.2=hfa1e0ec_1
  - icu=58.2=h4b95b61_1
  - imutils=0.5.3=py37_1
  - intel-openmp=2019.4=233
  - jasper=2.0.14=h636a363_1
  - jpeg=9b=he5867d9_2
  - kiwisolver=1.1.0=py37h0a44026_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libopencv=3.4.2=h7c891bd_1
  - libopus=1.3=h1de35cc_0
  - libpng=1.6.37=ha441bb4_0
  - libtiff=4.1.0=hcb84e12_0
  - libvpx=1.7.0=h378b8a2_0
  - libxml2=2.9.9=hf6e021a_1
  - matplotlib-base=3.0.3=py37habd5b94_1
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.15=py37h5e564d8_0
  - mkl_random=1.1.0=py37ha771720_0
  - ncurses=6.2=h0a44026_0
  - numpy=1.18.1=py37h7241aed_0
  - numpy-base=1.18.1=py37h6575580_1
  - opencv=3.4.2=py37h6fd60c2_1
  - openssl=1.1.1=h1de35cc_0
  - pcre=8.43=h0a44026_0
  - pip=20.0.2=py37_1
  - pixman=0.38.0=h1de35cc_0
  - py-opencv=3.4.2=py37h7c891bd_1
  - pyparsing=2.4.6=py_0
  - python=3.7.7=hc70fcce_0_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - readline=8.0=h1de35cc_0
  - scipy=1.4.1=py37h9fa6033_0
  - setuptools=46.1.3=py37_0
  - six=1.14.0=py37_0
  - sqlite=3.31.1=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - tornado=6.0.4=py37h9bfed18_1
  - wheel=0.34.2=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.3.7=h5bba6e5_0
  - pip:
    - pygame==1.9.6
prefix: /Users/peterdean/miniconda3/envs/PongNotPong

